apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app.kubernetes.io/name: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: hello
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello
    spec:
      containers:
        - name: hello-container
          image: busybox:1.31.1
          command: 
            - sh
            - -c
            - while true ; do printf '%s -- %s -- Hello!\n' "$( date '+%F %T' )" "$( hostname )" ; sleep 5 ; done
