#!/usr/bin/env bash

kubecli_man() {
	sed -n '/^# [+][+][+]$/,/^# [-][-][-]$/ {
		/^# [+][+][+]$/d
		/^# [-][-][-]$/d
		s/^# \?//p
	}'
}

exec < .kubecli
exec > README.md

kubecli_man | git-md-toc -cut
