#!/usr/bin/env bash

# https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/
# kubectl get pods -A --no-headers -o custom-columns=NAMES:.metadata.name,LABELS:.metadata.labels
kubecli() {
	cat - <<EXAMPLE
hello-7f6d6f64bc-4vk29             map[app.kubernetes.io/name:hello pod-template-hash:7f6d6f64bc]
hello-7f6d6f64bc-n9wz9             map[app.kubernetes.io/name:hello pod-template-hash:7f6d6f64bc]
coredns-74ff55c5b-9brbp            map[k8s-app:kube-dns pod-template-hash:74ff55c5b]
etcd-minikube                      map[component:etcd tier:control-plane]
kube-apiserver-minikube            map[component:kube-apiserver tier:control-plane]
kube-controller-manager-minikube   map[component:kube-controller-manager tier:control-plane]
kube-proxy-xphsp                   map[controller-revision-hash:b89db7f56 k8s-app:kube-proxy pod-template-generation:1]
kube-scheduler-minikube            map[component:kube-scheduler tier:control-plane]
storage-provisioner                map[addonmanager.kubernetes.io/mode:Reconcile integration-test:storage-provisioner]
EXAMPLE
}

for n in awk awk-sed awk-sed-column
do
	. kubecli-labels-$n
	kubecli-labels \
	| sort \
	> z-$n
done

winmerge z-awk z-awk-sed z-awk-sed-column &
