#!/usr/bin/env bash

kubecli-labels() {
	kubecli get "$@" \
	--no-headers \
	-o custom-columns=NAMES:.metadata.name,LABELS:.metadata.labels \
	| sed 's/map\[//; s/\]//; s/:/=/g' \
	| awk '
	{
		# collect pod names into the associative array with the
		# label names as keys of the array
		for (n = 2; n <= NF; n++) {
			s[$n] && s[$n] = s[$n] ","
			s[$n] = s[$n] $1
		}
	}

	END {
		# find a length of the longest label
		width = 0

		for (p in s) {
			len = length(p)
			len > width && width = len
		}

		# prepare the formatting string
		format = "%-" width "s  %s\n"

		# final work: output the labels and associated pods
		for (p in s) {
			printf format, p, s[p]
		}
	}
	'
}
